import type { Metadata } from "next";

import "./globals.css";
import Layout from "@/components/layout/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body>
        <Layout children={children} />
      </body>
    </html>
  );
}
