import type { Metadata } from "next";

import "./globals.css";
import Layout from "@/components/layout/layout";
import { Montserrat } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ['latin'], // 推荐指定字符子集以优化性能[citation:3][citation:4]
  display: 'swap', // 可选：控制字体加载期间的显示行为[citation:7]
  // 对于非可变字体，或者你只想使用特定字重，请配置 weight 参数[citation:3][citation:8]
  weight: ['400', '700'], // 例如，指定常规和粗体字重
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body className={montserrat.className}>
        <Layout children={children} />
      </body>
    </html>
  );
}
